FROM node:18.14.1

WORKDIR /app

ADD /package-lock.json /app/
ADD /package.json /app/


ADD /node_modules /app/node_modules/
ADD /public /app/public/
ADD /src /app/src/


EXPOSE 3000

CMD [ "npm" ,"run","start" ]